name: Publish
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install protobuf
        run: sudo apt install -y protobuf-compiler
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://npm.pkg.github.com/
          scope: "@faruuko"
      - name: Check version match
        uses: nick-y-ito/gha-npm-version-match@v1
      - name: Install dependencies
        run: yarn install
      - name: Genetate proto-ts
        run: yarn generate-protos
      - name: Build package
        run: yarn build
      - name: Authenticate
        run: echo "@faruuko:registry = https://npm.pkg.github.com/ //npm.pkg.github.com:_authToken=${{ secrets.ORM_OPERATIONS_ACCESS_TOKEN }}" > ~/.npmrc
      - name: Publish package
        run: yarn publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.ORM_OPERATIONS_ACCESS_TOKEN}}
