name: Publish
on:
  push:
    branches:
      - main
jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install protobuf
        run: sudo apt install -y protobuf-compiler

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          registry-url: https://npm.pkg.github.com/
          scope: "@faruuko"

      - name: Install dependencies
        run: yarn install

      - name: Run semantice release
        run: |
          yarn semantic-release
        working-directory: ${{ github.workspace }}

      - name: Print package.json version (before)
        run: |
          echo "package.json version (before): $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}

      - name: Fetch Latest Commit
        run: |
          git fetch
          git reset --hard origin/main

      - name: Print package.json version (after)
        run: |
          echo "package.json version (after): $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}

      - name: Genetate proto-ts
        run: yarn generate-protos

      - name: Build package
        run: yarn build

      - name: Print Build Version
        run: |
          echo "Build version: $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "protobuf $(jq -r .version package.json)"
          path: ${{ github.workspace }}/dist

  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1
          registry-url: https://npm.pkg.github.com/
          scope: "@faruuko"

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: "protobuf $(jq -r .version package.json)"
          path: ${{ github.workspace }}/dist

      - name: Authenticate
        run: echo "@faruuko:registry = https://npm.pkg.github.com/ //npm.pkg.github.com:_authToken=${{ secrets.ORM_OPERATIONS_ACCESS_TOKEN }}" > ~/.npmrc
      - name: Publish package
        run: yarn publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.ORM_OPERATIONS_ACCESS_TOKEN}}
